# container/Dockerfile
FROM node:20-bullseye-slim as builder
WORKDIR /app

COPY . .

RUN npm install
RUN npm run build
RUN npm run prisma:client

# If you truly need this sed step, be explicit:
# RUN sed -i 's/"src\//"dist\//g' package.json

FROM node:20-bullseye-slim
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY ./container/entrypoint.sh ./entrypoint.sh

RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]