version: '3.8'

services:
  app:
    env_file:
      - ../.env.local
    build:
      context: ..
      dockerfile: dev/Dockerfile
      args:
        NODE_ENV: development
    environment:
      NODE_ENV: development
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "3443:3443"
    depends_on:
      - db
    networks:
      - centinela-network

  db:
    image: postgres:15-alpine
    env_file:
      - ../.env.local
    ports:
      - "5433:5432"  # Changed to avoid conflict with local PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - centinela-network

volumes:
  postgres_data:

networks:
  centinela-network:
    driver: bridge